import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Divider, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'

const api = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'

type Session = { accessToken: string }
type CompanyItem = { id: string; tradeName: string; businessName: string; rfc: string }
type Paged<T> = { items: T[] }
type Customer360 = {
  company: { id:string; tradeName:string; businessName:string; rfc:string; customerType:string; status:string; email?:string; phone?:string; website?:string; address?:string; city?:string; state?:string; tags?:string }
  summary: { contacts:number; openOpportunities:number; openPipeline:number; pendingActivities:number; quotes:number; acceptedQuotes:number; licenses:number; expiringLicenses:number }
  contacts: Array<{ id:string; firstName:string; lastName:string; position?:string; email?:string; phone?:string; mobile?:string; isPrimary:boolean; isPurchasingContact:boolean; isTechnicalContact:boolean; isBillingContact:boolean }>
  opportunities: Array<{ id:string; name:string; productOrService?:string; estimatedAmount:number; probability:number; expectedCloseDateUtc?:string; stage:string; status:string; lossReason?:string }>
  quotes: Array<{ id:string; folio:string; title:string; currency:string; total:number; status:string; validUntilUtc:string; createdAtUtc:string }>
  activities: Array<{ id:string; type:string; subject:string; description?:string; dueAtUtc:string; priority:string; status:string }>
  licenses: Array<{ id:string; productName:string; serialNumber:string; version?:string; licenseType?:string; users:number; companies:number; expiresAtUtc:string; status:string; daysToExpire:number; pendingRenewals:number }>
}

export default function Customer360App(){
  const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[session,setSession]=useState<Session|null>(null); const[error,setError]=useState(''); const[loading,setLoading]=useState(false)
  async function login(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await fetch(`${api}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)throw new Error('Acceso incorrecto.');setSession(await r.json())}catch(x){setError(x instanceof Error?x.message:'Error')}finally{setLoading(false)}}
  if(!session)return <Container maxWidth="sm" sx={{py:10}}><Card><CardContent><Stack component="form" spacing={2} onSubmit={login}><Typography variant="overline">CRM MIDA</Typography><Typography variant="h4">Cliente 360°</Typography><Typography color="text.secondary">Consulta toda la relación comercial desde una sola vista.</Typography>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Correo" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><TextField label="Contraseña" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/><Button type="submit" variant="contained" disabled={loading}>{loading?<CircularProgress size={22}/>: 'Ingresar'}</Button></Stack></CardContent></Card></Container>
  return <Workspace token={session.accessToken}/>
}

function Workspace({token}:{token:string}){
  const headers=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]); const[companies,setCompanies]=useState<CompanyItem[]>([]); const[companyId,setCompanyId]=useState(''); const[data,setData]=useState<Customer360|null>(null); const[tab,setTab]=useState(0); const[loading,setLoading]=useState(false); const[error,setError]=useState('')
  useEffect(()=>{void (async()=>{const r=await fetch(`${api}/api/v1/companies?page=1&pageSize=100`,{headers});if(r.ok)setCompanies(((await r.json()) as Paged<CompanyItem>).items)})()},[])
  async function load(id=companyId){if(!id)return;setLoading(true);setError('');const r=await fetch(`${api}/api/v1/customers/${id}/360`,{headers});if(!r.ok){setError('No fue posible cargar Cliente 360°.');setLoading(false);return}setData(await r.json());setTab(0);setLoading(false)}
  const money=(v:number)=>v.toLocaleString('es-MX',{style:'currency',currency:'MXN'})
  return <Box minHeight="100vh" bgcolor="background.default"><Container maxWidth="xl" sx={{py:5}}><Stack spacing={3}>
    <Box><Typography variant="overline">Núcleo de relación con clientes</Typography><Typography variant="h3">Cliente 360°</Typography><Typography color="text.secondary">Contactos, pipeline, cotizaciones, actividades, licencias y renovaciones internas del CRM.</Typography></Box>
    {error&&<Alert severity="error">{error}</Alert>}
    <Paper sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField select fullWidth label="Empresa" value={companyId} onChange={e=>setCompanyId(e.target.value)}>{companies.map(c=><MenuItem key={c.id} value={c.id}>{c.tradeName} · {c.rfc}</MenuItem>)}</TextField><Button variant="contained" onClick={()=>void load()} disabled={!companyId||loading}>Abrir Cliente 360°</Button></Stack></Paper>
    {loading&&<Box textAlign="center"><CircularProgress/></Box>}
    {data&&<>
      <Paper sx={{p:3}}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h4">{data.company.tradeName}</Typography><Typography>{data.company.businessName}</Typography><Typography color="text.secondary">RFC {data.company.rfc} · {data.company.customerType}</Typography></Box><Stack direction="row" spacing={1} flexWrap="wrap"><Chip label={data.company.status}/>{data.company.tags&&<Chip variant="outlined" label={data.company.tags}/>}</Stack></Stack><Divider sx={{my:2}}/><Typography>{[data.company.email,data.company.phone,data.company.city,data.company.state].filter(Boolean).join(' · ')}</Typography></Paper>
      <Box sx={{display:'grid',gridTemplateColumns:{xs:'repeat(2,1fr)',md:'repeat(4,1fr)'},gap:2}}>{[
        ['Contactos',data.summary.contacts],['Oportunidades abiertas',data.summary.openOpportunities],['Pipeline',money(data.summary.openPipeline)],['Actividades pendientes',data.summary.pendingActivities],['Cotizaciones',data.summary.quotes],['Cotizaciones aceptadas',money(data.summary.acceptedQuotes)],['Licencias',data.summary.licenses],['Vencen ≤ 90 días',data.summary.expiringLicenses]
      ].map(([label,value])=><Card key={String(label)}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h5">{value}</Typography></CardContent></Card>)}</Box>
      <Paper><Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto"><Tab label="Resumen"/><Tab label={`Contactos (${data.contacts.length})`}/><Tab label={`Oportunidades (${data.opportunities.length})`}/><Tab label={`Cotizaciones (${data.quotes.length})`}/><Tab label={`Actividades (${data.activities.length})`}/><Tab label={`Licencias (${data.licenses.length})`}/></Tabs><Divider/><Box sx={{p:3}}>
        {tab===0&&<Stack spacing={2}><Typography variant="h6">Información general</Typography><Typography>{data.company.address||'Sin dirección registrada'}</Typography><Typography>{data.company.website||'Sin sitio web registrado'}</Typography></Stack>}
        {tab===1&&<Stack spacing={1}>{data.contacts.length===0?<Typography>Sin contactos.</Typography>:data.contacts.map(x=><Card variant="outlined" key={x.id}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{x.firstName} {x.lastName}</Typography><Typography variant="body2">{x.position||x.email||'Sin puesto'}</Typography><Typography variant="body2">{x.email} {x.mobile||x.phone}</Typography></Box>{x.isPrimary&&<Chip label="Principal" color="primary"/>}</Stack></CardContent></Card>)}</Stack>}
        {tab===2&&<Stack spacing={1}>{data.opportunities.length===0?<Typography>Sin oportunidades.</Typography>:data.opportunities.map(x=><Card variant="outlined" key={x.id}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{x.name}</Typography><Typography variant="body2">{x.productOrService} · {x.stage}</Typography></Box><Box textAlign="right"><Typography fontWeight={700}>{money(x.estimatedAmount)}</Typography><Chip size="small" label={`${x.probability}% · ${x.status}`}/></Box></Stack></CardContent></Card>)}</Stack>}
        {tab===3&&<Stack spacing={1}>{data.quotes.length===0?<Typography>Sin cotizaciones.</Typography>:data.quotes.map(x=><Card variant="outlined" key={x.id}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{x.folio} · {x.title}</Typography><Typography variant="body2">Vigencia {new Date(x.validUntilUtc).toLocaleDateString()}</Typography></Box><Box textAlign="right"><Typography fontWeight={700}>{x.currency} {x.total.toLocaleString('es-MX')}</Typography><Chip size="small" label={x.status}/></Box></Stack></CardContent></Card>)}</Stack>}
        {tab===4&&<Stack spacing={1}>{data.activities.length===0?<Typography>Sin actividades.</Typography>:data.activities.map(x=><Card variant="outlined" key={x.id}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{x.subject}</Typography><Typography variant="body2">{x.description}</Typography><Typography variant="caption">{new Date(x.dueAtUtc).toLocaleString()}</Typography></Box><Chip size="small" label={`${x.priority} · ${x.status}`}/></Stack></CardContent></Card>)}</Stack>}
        {tab===5&&<Stack spacing={1}>{data.licenses.length===0?<Typography>Sin licencias internas.</Typography>:data.licenses.map(x=><Card variant="outlined" key={x.id}><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{x.productName}</Typography><Typography variant="body2">Serie {x.serialNumber} · Versión {x.version||'N/D'}</Typography><Typography variant="caption">Vence {new Date(x.expiresAtUtc).toLocaleDateString()}</Typography></Box><Box textAlign="right"><Chip size="small" color={x.status==='expired'?'error':x.status==='expiring'?'warning':'success'} label={`${x.status} · ${x.daysToExpire} días`}/>{x.pendingRenewals>0&&<Typography variant="caption" display="block">Renovación pendiente</Typography>}</Box></Stack></CardContent></Card>)}</Stack>}
      </Box></Paper>
    </>}
  </Stack></Container></Box>
}
