import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Add, Autorenew, History } from '@mui/icons-material'
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'

const api = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'
interface Session { accessToken: string }
interface Company { id: string; tradeName: string }
interface License { id:string; companyId:string; companyName:string; productName:string; serialNumber:string; version?:string; licenseType?:string; users:number; companies:number; startsAtUtc:string; expiresAtUtc:string; status:string; daysToExpire:number; notes?:string }
interface Dashboard { expired:number; expiring30:number; expiring60:number; expiring90:number; active:number; total:number }
interface Renewal { id:string; targetDateUtc:string; estimatedAmount:number; status:string; opportunityId?:string; notes?:string; createdAtUtc:string; completedAtUtc?:string }

export default function LicensesApp(){
 const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[session,setSession]=useState<Session|null>(null); const[error,setError]=useState('')
 async function login(e:FormEvent){e.preventDefault();const r=await fetch(`${api}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)return setError('Acceso incorrecto.');setSession(await r.json())}
 if(!session)return <Container maxWidth="sm" sx={{py:10}}><Card><CardContent><Stack component="form" spacing={2} onSubmit={login}><Typography variant="h4">Licencias MIDA</Typography>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><TextField label="Contraseña" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><Button type="submit" variant="contained">Ingresar</Button></Stack></CardContent></Card></Container>
 return <Workspace token={session.accessToken}/>
}

function Workspace({token}:{token:string}){
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`}),[token]); const[licenses,setLicenses]=useState<License[]>([]); const[companies,setCompanies]=useState<Company[]>([]); const[dash,setDash]=useState<Dashboard|null>(null); const[loading,setLoading]=useState(true); const[error,setError]=useState(''); const[dialog,setDialog]=useState(false); const[history,setHistory]=useState<Renewal[]>([]); const[historyOpen,setHistoryOpen]=useState(false)
 const[form,setForm]=useState({companyId:'',productName:'',serialNumber:'',version:'',licenseType:'anual',users:1,companies:1,startsAtUtc:new Date().toISOString().slice(0,10),expiresAtUtc:new Date(Date.now()+365*86400000).toISOString().slice(0,10),notes:''})
 async function load(){setLoading(true);try{const[lr,dr,cr]=await Promise.all([fetch(`${api}/api/v1/licenses`,{headers}),fetch(`${api}/api/v1/licenses/dashboard`,{headers}),fetch(`${api}/api/v1/companies?page=1&pageSize=100`,{headers})]);if(!lr.ok||!dr.ok||!cr.ok)throw new Error('No fue posible cargar licencias.');setLicenses(await lr.json());setDash(await dr.json());setCompanies((await cr.json()).items)}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function save(e:FormEvent){e.preventDefault();const r=await fetch(`${api}/api/v1/licenses`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({...form,startsAtUtc:new Date(`${form.startsAtUtc}T12:00:00Z`).toISOString(),expiresAtUtc:new Date(`${form.expiresAtUtc}T12:00:00Z`).toISOString()})});if(!r.ok)return setError('No fue posible registrar la licencia.');setDialog(false);await load()}
 async function createRenewal(x:License){const amount=Number(prompt('Monto estimado de renovación','0')??'0');const r=await fetch(`${api}/api/v1/licenses/${x.id}/renewals`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({targetDateUtc:x.expiresAtUtc,estimatedAmount:amount})});if(!r.ok)return setError('No fue posible crear la renovación.');alert('Renovación y oportunidad comercial creadas.')}
 async function openHistory(id:string){const r=await fetch(`${api}/api/v1/licenses/${id}/renewals`,{headers});setHistory(r.ok?await r.json():[]);setHistoryOpen(true)}
 const cards=[['Total',dash?.total],['Vencidas',dash?.expired],['≤ 30 días',dash?.expiring30],['31–60 días',dash?.expiring60],['61–90 días',dash?.expiring90],['> 90 días',dash?.active]]
 return <Box minHeight="100vh" bgcolor="background.default"><Container maxWidth="xl" sx={{py:5}}><Stack spacing={3}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between"><Box><Typography variant="overline">Sprint 5</Typography><Typography variant="h4">Licencias y renovaciones</Typography></Box><Button variant="contained" startIcon={<Add/>} onClick={()=>setDialog(true)}>Nueva licencia</Button></Stack>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}<Grid container spacing={2}>{cards.map(([label,value])=><Grid item xs={6} md={2} key={String(label)}><Card><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{value??0}</Typography></CardContent></Card></Grid>)}</Grid><TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Empresa</TableCell><TableCell>Producto</TableCell><TableCell>Serie</TableCell><TableCell>Vence</TableCell><TableCell>Días</TableCell><TableCell>Estado</TableCell><TableCell>Acciones</TableCell></TableRow></TableHead><TableBody>{loading?<TableRow><TableCell colSpan={7} align="center"><CircularProgress/></TableCell></TableRow>:licenses.map(x=><TableRow key={x.id}><TableCell>{x.companyName}</TableCell><TableCell>{x.productName}</TableCell><TableCell>{x.serialNumber}</TableCell><TableCell>{new Date(x.expiresAtUtc).toLocaleDateString()}</TableCell><TableCell>{x.daysToExpire}</TableCell><TableCell><Chip size="small" label={x.status} color={x.status==='expired'?'error':x.status==='expiring'?'warning':'success'}/></TableCell><TableCell><Button size="small" startIcon={<Autorenew/>} onClick={()=>void createRenewal(x)}>Renovar</Button><Button size="small" startIcon={<History/>} onClick={()=>void openHistory(x.id)}>Historial</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></Stack></Container>
 <Dialog open={dialog} onClose={()=>setDialog(false)} fullWidth maxWidth="md"><Stack component="form" onSubmit={save}><DialogTitle>Nueva licencia</DialogTitle><DialogContent><Grid container spacing={2} sx={{pt:1}}><Grid item xs={12}><TextField select fullWidth required label="Empresa" value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})}>{companies.map(c=><MenuItem key={c.id} value={c.id}>{c.tradeName}</MenuItem>)}</TextField></Grid><Grid item xs={12} md={6}><TextField fullWidth required label="Producto" value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})}/></Grid><Grid item xs={12} md={6}><TextField fullWidth required label="Serie" value={form.serialNumber} onChange={e=>setForm({...form,serialNumber:e.target.value})}/></Grid><Grid item xs={6} md={3}><TextField fullWidth label="Versión" value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></Grid><Grid item xs={6} md={3}><TextField fullWidth label="Tipo" value={form.licenseType} onChange={e=>setForm({...form,licenseType:e.target.value})}/></Grid><Grid item xs={6} md={3}><TextField fullWidth type="number" label="Usuarios" value={form.users} onChange={e=>setForm({...form,users:Number(e.target.value)})}/></Grid><Grid item xs={6} md={3}><TextField fullWidth type="number" label="Empresas" value={form.companies} onChange={e=>setForm({...form,companies:Number(e.target.value)})}/></Grid><Grid item xs={6}><TextField fullWidth type="date" label="Inicio" InputLabelProps={{shrink:true}} value={form.startsAtUtc} onChange={e=>setForm({...form,startsAtUtc:e.target.value})}/></Grid><Grid item xs={6}><TextField fullWidth type="date" label="Vencimiento" InputLabelProps={{shrink:true}} value={form.expiresAtUtc} onChange={e=>setForm({...form,expiresAtUtc:e.target.value})}/></Grid></Grid></DialogContent><DialogActions><Button onClick={()=>setDialog(false)}>Cancelar</Button><Button type="submit" variant="contained">Guardar</Button></DialogActions></Stack></Dialog>
 <Dialog open={historyOpen} onClose={()=>setHistoryOpen(false)} fullWidth><DialogTitle>Historial de renovaciones</DialogTitle><DialogContent>{history.length===0?<Typography>Sin renovaciones.</Typography>:history.map(r=><Card key={r.id} sx={{mb:1}}><CardContent><Typography fontWeight={700}>{r.status}</Typography><Typography variant="body2">Objetivo: {new Date(r.targetDateUtc).toLocaleDateString()} · {r.estimatedAmount.toLocaleString('es-MX',{style:'currency',currency:'MXN'})}</Typography>{r.notes&&<Typography variant="body2">{r.notes}</Typography>}</CardContent></Card>)}</DialogContent></Dialog>
 </Box>
}
